/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import Codigo.*;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author user2
 */
public class AgregarAlum extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAlum
     */
    private Table table;
    public AgregarAlum(Table table) {
        initComponents();
        this.setTitle("Agregar Alumno");
        this.table = table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txbNombreAlum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txbApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbCursoAlumno = new javax.swing.JComboBox();
        bAcepAlum = new javax.swing.JButton();
        bCanAlum = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txbObv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbmFalta = new javax.swing.JComboBox();

        jLabel3.setText("jLabel3");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        txbNombreAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbNombreAlumActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido:");

        txbApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbApellidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Curso:");

        cmbCursoAlumno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1ºA", "1ºB", "1ºC" }));
        cmbCursoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursoAlumnoActionPerformed(evt);
            }
        });

        bAcepAlum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        bAcepAlum.setText("Aceptar");
        bAcepAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcepAlumActionPerformed(evt);
            }
        });

        bCanAlum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        bCanAlum.setText("Cancelar");
        bCanAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCanAlumActionPerformed(evt);
            }
        });

        jLabel5.setText("Observaciones:");

        txbObv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbObvActionPerformed(evt);
            }
        });

        jLabel6.setText("Asistencia:");

        cbmFalta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Presente", "Ausente" }));
        cbmFalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmFaltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txbNombreAlum, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txbApellido)))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bCanAlum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAcepAlum)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txbObv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCursoAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbmFalta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txbNombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbObv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbmFalta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCursoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCanAlum)
                    .addComponent(bAcepAlum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txbApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbApellidoActionPerformed

    private void bCanAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCanAlumActionPerformed
       dispose();
    }//GEN-LAST:event_bCanAlumActionPerformed

    private void bAcepAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcepAlumActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getTblAlum().getModel(); 
        try {
            boolean asistio=true;
            if(cbmFalta.getSelectedIndex()==0) {  
                System.out.println("presesnte");
                asistio = true;
            }
            else { 
                System.out.println("ausente");
                asistio = false;
            }
            
            Alumnos alum = new Alumnos(txbNombreAlum.getText(),txbApellido.getText()
                    , asistio,Integer.parseInt(txbObv.getText())
                    ,(String) cmbCursoAlumno.getSelectedItem());          
            if (ListaAlumnos.addAlumnos(alum)){                
//                model.addRow(new Object[]{alum.getNombre(),alum.getApellido(),alum.getObvsrvacion()});

                txbNombreAlum.setText("");       
                txbApellido.setText("");
                cbmFalta.setSelectedIndex(0);
                txbObv.setText("");
                cmbCursoAlumno.setSelectedIndex(0);
                
                JOptionPane.showMessageDialog(this, "Se cargo correctamente");
                ListaAlumnos.saveLista();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No hay mas lugar");
                dispose();
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
            
            dispose();
            
        } 
       
    }//GEN-LAST:event_bAcepAlumActionPerformed

    private void txbObvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbObvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbObvActionPerformed

    private void cmbCursoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCursoAlumnoActionPerformed

    private void cbmFaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmFaltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmFaltaActionPerformed

private void txbNombreAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbNombreAlumActionPerformed
 // TODO add your handling code here:
}//GEN-LAST:event_txbNombreAlumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AgregarAlum(new Table()).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAcepAlum;
    private javax.swing.JButton bCanAlum;
    private javax.swing.JComboBox cbmFalta;
    private javax.swing.JComboBox cmbCursoAlumno;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txbApellido;
    private javax.swing.JTextField txbNombreAlum;
    private javax.swing.JTextField txbObv;
    // End of variables declaration//GEN-END:variables



}
